### ISSUE TITLE
Class Summary

### ISSUE THREAD

**Issue by justin-to** [aegarro/WanderDots#7]
(https://github.com/aegarro/WanderDots/blob/master/app/src/main/java/WanderDots/Experience.java)
There should be a short summary for this class: what is in this class and what this class does.

**Comment by azilvitis** [comment]
/* Provides the super class functionality of Dot and Adventure
 * 1. Provides: Categories, PictureIds, Description, Creator, Location
 * 2. Provides: abstract methods stubs for Dot and Adventure
 */
